apiVersion: v1

kind: Pod

metadata:
  name: pod4
  labels:
    tier: frontend
    env: prod
    city: Pune
    color: Green

spec:
  containers:
    - name: cont1
      image: nginx
    - name: cont2
      image: redis
