apiVersion: v1

kind: ReplicationController

metadata:
  name: my-rc

spec:
  replicas: 3
  selector:
    app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: cont1
          image: nginx

