apiVersion: v1

kind: Service

metadata:
  name: websvc

spec:
  type: ClusterIP
  selector:
    env: test
  ports:
    - name: port1
      protocol: TCP
      port: 8080      # Port exposed to consumers
      targetPort: 80  # port of the pod hosting the application
