apiVersion: apps/v1

kind: ReplicaSet

metadata:
  name: my-rs-a

spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: cont1
          image: nginx

