apiVersion: v1

kind: Service

metadata:
  name: nport1

spec:
  type: NodePort
  selector:
    env: test
  ports:
    - name: port1
      protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 31677
