apiVersion: v1

kind: Pod

metadata:
  name: pod4

spec:
  volumes:
    - name: vol1
      gitRepo:
        repository: https://github.com/algorithm-visualizer/algorithm-visualizer.git
        revision: master
        directory: .
  containers:
    - name: cont1
      image: nginx
      volumeMounts:
        - name: vol1
          mountPath: /ramakant-dir
    - name: cont2
      image: redis
      volumeMounts:
        - name: vol1
          mountPath: /repoData

