apiVersion: v1

kind: Pod

metadata:
  name: pod5

spec:
  volumes:
    - name: vol1
      hostPath:
        path: /locationData
  containers:
    - name: cont1
      image: nginx
      volumeMounts:
        - name: vol1
          mountPath: /ramakant-dir

