apiVersion: v1
kind: Pod

metadata:
  name: pod1

spec:
  containers:
    - name: cont1
      image: debian
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo Hello; sleep 2; done"]
  restartPolicy: OnFailure
