apiVersion: v1
kind: Pod

metadata:
  name: pod2

spec:
  containers:
    - name: cont1
      image: nginx
      env:
        - name: MY_DB_USER
          valueFrom:
            configMapKeyRef:
              name: cm2
              key: username
