apiVersion: v1
kind: Pod

metadata:
  name: pod1

spec:
  containers:
    - name: cont1
      image: nginx
      env:
        - name: MY_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sec1
              key: password
