apiVersion: apps/v1
kind: Deployment

metadata:
  name: olddp

spec:
  replicas: 3
  selector:
    matchLabels:
      app: v1
  template:
    metadata:
      labels:
        app: v1
    spec:
      containers:
        - name: cont1
          image: nginx:1.14.2

