apiVersion: apps/v1
kind: Deployment

metadata:
  name: newdp

spec:
  replicas: 3
  selector:
    matchLabels:
      app: v2
  template:
    metadata:
      labels:
        app: v2
    spec:
      containers:
        - name: cont1
          image: nginx:1.21

