apiVersion: v1
kind: Pod

metadata:
  name: pod3

spec:
  containers:
    - name: cont1
      image: nginx:latest
      ports:
        - containerPort: 80
          hostPort: 8080
          protocol: TCP
